<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Catalyst.Presidio</PackageId>
    <Description>Catalyst.Presidio is a PII detection and anonymization library based on Catalyst.</Description>
    <PackageTags>PII, NLP, Presidio, Anonymization, Data Protection</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mosaik.Core" Version="26.8.3972" />
    <PackageReference Include="MessagePack" Version="3.1.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catalyst\Catalyst.csproj" />
  </ItemGroup>

</Project>
