variables:
  solution: '**/*.sln'
  project:  './Catalyst/Catalyst.csproj'
  projectSpacy:  './Catalyst.Spacy/Catalyst.Spacy.csproj'
  projectWordNet:  './Catalyst.WordNet/Catalyst.WordNet.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - Languages
    - samples
    - Catalyst.Training
    - Catalyst.WordNet.Test
    - tests
    - azure-devops/build-models.yml

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  lfs: true

- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET 8.0 SDK'
  inputs:
    packageType: sdk
    version: 8.x
    includePreviewVersions: false
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'restore nuget'
  inputs:
    command: 'restore'
    projects: '$(project)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '-c $(buildConfiguration) /p:Version=1.0.$(build.buildId)  /p:AllowUnsafeBlocks=True /p:LangVersion=latest'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projectSpacy)'
    arguments: '-c $(buildConfiguration) /p:Version=1.0.$(build.buildId)  /p:AllowUnsafeBlocks=True /p:LangVersion=latest'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projectWordNet)'
    arguments: '-c $(buildConfiguration) /p:Version=1.0.$(build.buildId)  /p:AllowUnsafeBlocks=True /p:LangVersion=latest'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '$(project)'
    versioningScheme: 'off'
    configuration: 'Release'
    buildProperties: 'Version="1.0.$(build.buildId)";AllowUnsafeBlocks="True";LangVersion="latest"'
    verbosityPack: 'Diagnostic'
    nobuild: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '$(projectSpacy)'
    versioningScheme: 'off'
    configuration: 'Release'
    buildProperties: 'Version="1.0.$(build.buildId)";AllowUnsafeBlocks="True";LangVersion="latest"'
    verbosityPack: 'Diagnostic'
    nobuild: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '$(projectWordNet)'
    versioningScheme: 'off'
    configuration: 'Release'
    buildProperties: 'Version="1.0.$(build.buildId)";AllowUnsafeBlocks="True";LangVersion="latest"'
    verbosityPack: 'Diagnostic'
    nobuild: true

- task: NuGetCommand@2
  displayName: 'push nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity-org'
