<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net70</TargetFramework>
    <AssemblyName>EntityRecognition</AssemblyName>
    <RootNamespace>Catalyst.Samples.EntityRecognition</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Catalyst" Version="26.9.5306" />
    <PackageReference Include="Catalyst.Models.English" Version="1.0.30952" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
  </ItemGroup>
</Project>
